# Generated by Django 4.2.10 on 2024-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minidescription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
