# Generated by Django 4.2.10 on 2024-03-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_image_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
