# Generated by Django 4.2.10 on 2024-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Ссылка на изображение'),
            preserve_default=False,
        ),
    ]
